name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build with Buildozer Action
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        workdir: .
        buildozer_version: stable

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: counterapp-apk
        path: bin/*.apk
