name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Docker
      run: |
        sudo apt update
        sudo apt install -y docker.io

    - name: Build with Buildozer Docker
      run: |
        docker run --rm -v ${{ github.workspace }}:/home/user/hostcwd \
        kivy/buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: counterapp-apk
        path: bin/*.apk
